services:
  - type: web
    name: betplay-telegram-bot
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: bash render_start.sh
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: FOOTBALL_DATA_API_KEY
        sync: false
      - key: ODDS_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
