football_data_org:
  api_key: ""
  competitions: ["PL","PD","SA","BL1","FL1","DED","PPL"]

the_odds_api:
  api_key: "627daa563fac7747f4ed83a8d86ace6d"
  base_url: "https://api.the-odds-api.com/v4"

api_football:
  base_url: "https://v3.football.api-sports.io"
  api_key: "OPCIONAL_API_FOOTBALL_SI ALGÚN DÍA PAGAS"
  leagues: [39,140,135,78,61]  # ejemplo: EPL, LaLiga, Serie A, Bundesliga, Ligue1
